version: '3.8'

services:
  lais-ia-backend:
    build: .
    container_name: lais-ia-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Usar .env.production para production
      - NODE_ENV=production
      - PORT=8000
      
      # URLs da ROI Labs
      - WEBHOOK_URL=https://lais-ia-api.roilabs.com.br
      - FRONTEND_URL=https://lais-ia.roilabs.com.br
      
      # N8N Integration - JÁ CONFIGURADO!
      - N8N_WEBHOOK_URL=https://n8n.roilabs.com.br
      - N8N_API_KEY=${N8N_API_KEY}
      - ENABLE_N8N=true
      
      # Supabase Database - PRODUCTION
      - DATABASE_URL=${SUPABASE_DATABASE_URL}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      
      # Redis Cache - ROI Labs
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      
      # Evolution API
      - EVOLUTION_API_URL=${EVOLUTION_API_URL}
      - EVOLUTION_API_KEY=${EVOLUTION_API_KEY}
      - EVOLUTION_INSTANCE_NAME=lais_ia_roilabs
      
      # Claude AI
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - CLAUDE_MODEL=claude-3-5-sonnet-20241022
      
      # Security
      - JWT_SECRET=${JWT_SECRET}
      
      # Company
      - COMPANY_NAME=ROI Labs
      - COMPANY_PHONE=${COMPANY_PHONE}
      - COMPANY_EMAIL=contato@roilabs.com.br
      
      # EasyPanel specifics
      - VIRTUAL_HOST=lais-ia-api.roilabs.com.br
      - LETSENCRYPT_HOST=lais-ia-api.roilabs.com.br
      - LETSENCRYPT_EMAIL=contato@roilabs.com.br
      
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      - ./backups:/app/backups
    
    networks:
      - roilabs-network
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # Logging
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx proxy para SSL (opcional se EasyPanel já gerencia)
  nginx-proxy:
    image: nginx:alpine
    container_name: lais-ia-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl-certs:/etc/nginx/ssl:ro
    depends_on:
      - lais-ia-backend
    networks:
      - roilabs-network
    profiles:
      - nginx  # Ativar apenas se necessário

networks:
  roilabs-network:
    driver: bridge
    name: roilabs-network

# Volumes para persistência
volumes:
  logs:
    driver: local
  uploads:
    driver: local
  backups:
    driver: local
