name: Feature Request
description: Suggest a new feature or improvement for Sofia AI
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please describe your idea clearly.
        For major architectural changes, please consider opening an [RFC](../../docs/RFC-PROCESS.md) instead.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Who would benefit from it?
      placeholder: "I'm always frustrated when... / As a [user type], I need to..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like. Include mockups, examples, or code snippets if possible.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered.
    validations:
      required: false

  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      options:
        - New integration (new provider, API)
        - UI/UX improvement
        - Performance improvement
        - New AI capability (tool, memory, etc.)
        - Developer experience (SDK, API, docs)
        - Enterprise feature (SSO, RBAC, audit)
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Perceived Priority
      options:
        - P0 - Critical (blocking my use case)
        - P1 - High (important improvement)
        - P2 - Medium (nice to have)
        - P3 - Low (future consideration)
    validations:
      required: false

  - type: checkboxes
    id: willingness
    attributes:
      label: Contribution
      options:
        - label: I'm willing to submit a PR to implement this feature
        - label: I need help implementing this if accepted

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or references.
    validations:
      required: false
